### ISSUE TITLE
Arousal increases significantly higher when the threshold is lower.

### ISSUE THREAD

**Issue by MauAbata** [MausTec/edge-o-matic-3000#36]
The arousal sensitivity should be decoupled from the calculation, and the threshold should purely be a threshold, with a separate setting for how sensitive increases are.

Otherwise, when lower arousal settings are used, tiny pressure fluctuations cause really large jumps. Temporary solution is to use pressure smoothing at 5 samples and calculate arousal on averages.

Warranty 70008

**Comment by B4ben-69** [comment]
Hi Mau, is this issue in relation to my clench detector? if it is, yes a long clench is assumed to be an arousal increase. The clench detector (Using clench in edging) is normally off in the edgeOrgasm menus.

I personally turn on clench detector in edging because my body does not twitch when i get close to a orgasm. It clenches, so the duration of the clench says how close i am to the edge. 
Using the clench detector combined the vibrator "Depletion" Mode forces my body in an uncontrolled resonance that edges particularly effectively. The threshold needs to be raised gradually to reach this point.

**Comment by MauAbata** [comment]
I don't really think this is related to the clench detection, it's been doing this before that was added.

Originally, "arousal limit" was a sensitivity setting in general, so the lower the limit the higher the sensitivity, and thus it scaled the arousal values higher. I haven't looked into this yet to see where that scaling is happening.

**Comment by MauAbata** [comment]
I don't really think this is related to the clench detection, it's been doing this before that was added.

Originally, "arousal limit" was a sensitivity setting in general, so the lower the limit the higher the sensitivity, and thus it scaled the arousal values higher. I haven't looked into this yet to see where that scaling is happening.
